### ISSUE TITLE
Failing to create a submission

### ISSUE THREAD

**Issue by ryshoooo** [openanalytics/RDepot-client#1]
I'm trying to use the UI to submit a package, but failing to do so. I'm using rdepot 2.1.1 and when trying to upload a cowplot package, I get a message that the package has an incorrect extension, even though the extension is correct. See the image below.

How can I resolve this?

<img width="1320" alt="Screenshot 2024-06-26 at 14 34 25" src="https://github.com/openanalytics/RDepot-client/assets/12965813/d69c6e9b-ded1-4c3d-9b7a-8c1d5ed34c59">

**Comment by ryshoooo** [comment]
I did a bit of debugging and found out that my packages are of type `application-xgzip`, not just `application-gzip`, which is where the check fails

**Comment by jvanmalder** [comment]
Hi @ryshoooo - thanks for the feature request and suggested solution in your PR. This is now part of release 2.3.0.

**Comment by jvanmalder** [comment]
Hi @ryshoooo - thanks for the feature request and suggested solution in your PR. This is now part of release 2.3.0.
